### ISSUE TITLE
Support of \MongoCode by extension < 1.2.0

### ISSUE THREAD

**Issue by sokil** [alcaeus/mongo-php-adapter#197] opened 2017-09-11 07:11 UTC
I run my tests on php 7.0 with travis: https://travis-ci.org/sokil/php-mongo/jobs/274059877
There is preisnatlled MongoDb extension with version 1.2.0-dev
```
$ php -r 'echo MONGODB_VERSION . PHP_EOL;'; fi
1.2.0-dev
```

And my tests broken on:

```
1) Sokil\Mongo\DocumentTest::testSetMongoCode
Error: Call to undefined method MongoDB\BSON\Javascript::getCode()
/home/travis/build/sokil/php-mongo/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCode.php:43
/home/travis/build/sokil/php-mongo/vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/TypeConverter.php:165
/home/travis/build/sokil/php-mongo/vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/TypeConverter.php:77
/home/travis/build/sokil/php-mongo/vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/TypeConverter.php:180
/home/travis/build/sokil/php-mongo/vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/TypeConverter.php:77
/home/travis/build/sokil/php-mongo/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php:563
/home/travis/build/sokil/php-mongo/src/Cursor.php:482
/home/travis/build/sokil/php-mongo/src/Collection.php:634
/home/travis/build/sokil/php-mongo/tests/DocumentTest.php:554
```

https://github.com/alcaeus/mongo-php-adapter/blob/master/lib/Mongo/MongoCode.php#L41-L45

```
        if ($code instanceof \MongoDB\BSON\Javascript) {
            $javascript = $code;
            $code = $javascript->getCode();
            $scope = TypeConverter::toLegacy($javascript->getScope());
        }
```

This code fails with `Call to undefined method MongoDB\BSON\Javascript::getCode()`

**Comment by jmikola** [comment] 2017-09-19 20:18
`Javascript::getCode()` was implemented in https://github.com/mongodb/mongo-php-driver/commit/98f02d868c3bbfb53df4d22dc937190895ec1795 and has been available since [1.2.0alpha1](https://pecl.php.net/package/mongodb/1.2.0alpha1).

Since the extension reports its version as 1.2.0-dev, it's possible that you're using a version that was compiled before the 1.2.0alpha1 release. That may be due to Travis CI historically installing the mongodb extension on PHP 7.x by compiling the [mongo-php-driver](https://github.com/mongodb/mongo-php-driver) master branch instead of using `pecl install mongodb`, which would have grabbed the most recent, stable release.

I submitted a patch to Travis' PHP build tools in https://github.com/travis-ci/php-src-builder/commit/33f4aebe1e553eb54c77519d4ce4191b7fb04a96, so that the the extension's master branch is only used for PHP nightly and snapshot environments (described in https://github.com/travis-ci/travis-ci/issues/7268).

As for why your Travis environment still has 1.2.0-dev installed, despite my patch to php-src-builder, comments in https://github.com/travis-ci/travis-ci/issues/8399#issuecomment-330578503 may shed some light on that:

> 7.2.0RC1 was archived before the additional changes that affected excluded `^7` versions; so it did not run `pecl install mongodb`.

If we assume that Travis is still using several PHP environments that were created and archived/deployed before my patch, those may still have a `mongodb.so` file that was compiled from the master branch. Looking at your [build matrix](https://travis-ci.org/sokil/php-mongo/builds/274059874), I see that only the "7.0" environment failed. It's likely that the `mongodb.so` file available in that environment was compiled from [mongo-php-driver](https://github.com/mongodb/mongo-php-driver)'s master branch before we tagged 1.2.0alpha1. [This line](https://travis-ci.org/sokil/php-mongo/jobs/274059877#L464) from your failed build reports:

```
PHP 7.0.7 (cli) (built: May 26 2016 23:56:29) ( ZTS )
```

That is well before we released [1.2.0alpha1](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0alpha1) on August 4, 2016.

I would suggest the following steps to work around this issue:

 * Remove the steps for [Enable preinstalled PHP extensions](https://docs.travis-ci.com/user/languages/php#Enabling-preinstalled-PHP-extensions) from your existing configuration.
 * Manually install the latest, stable version of the extension by calling `pecl install -f mongodb` as a `before_script` step. Installing via PECL should enable the extension in PHP's INI configuration for you (as noted in 
https://github.com/travis-ci/travis-ci/issues/8399#issuecomment-330623040).

I might also suggest opening an issue on [travis-ci/travis-ci](https://github.com/travis-ci/travis-ci) to request that they regenerate their PHP 7.0 and 7.1 environments, since it's likely that both are carrying unstable builds of `mongodb.so`. Feel free to refer back to this comment to provide some context to that issue.

**Comment by jmikola** [comment] 2017-09-19 20:21
@alcaeus: Since you already correctly require [`^1.2.0`](https://github.com/alcaeus/mongo-php-adapter/blob/1d75ce67c9362848ef05c17824bd5a5e370d2930/composer.json#L14) for `ext-mongodb`, I'm not sure that a fix is warranted in your library. Does Composer allow "1.2.0-dev" to satisfy a `^1.2.0` version requirement? I wouldn't expect so, unless it's being lax with extension versions.

**Comment by alcaeus** [comment] 2017-09-20 07:16
@jmikola thanks for investigating this! IIRC, composer uses `version_compare`, which correctly identifies `1.2.0-dev` as not satisfying `1.2.0`:
```
php > var_dump(version_compare('1.2.0-dev', '1.2.0', '>'));
php shell code:1:
bool(false)
```

I'll create a branch to test against the built-in (dev version) of the 1.2.0 extension to try and reproduce the error.

**Comment by alcaeus** [comment] 2017-09-22 07:02
I tested this in #202, but travis seem to have updated their built-in extension: https://travis-ci.org/alcaeus/mongo-php-adapter/builds/278501813#L485

With that in mind, I'd close the issue. Not sure why composer didn't pick up on the version constraint, but I'll revisit this only if there's another problem with 1.3.0-dev.

**Closed by alcaeus** 2017-09-22 07:02 UTC
