### ISSUE TITLE
 Nesting level too deep - recursive dependency?

### ISSUE THREAD

**Issue by ArabCoders** [alcaeus/mongo-php-adapter#106] opened 2016-05-01 06:49 UTC
Hello,

this error keep poping up lately, for unknown reason, it might have something to do with upgrading to PHP 7 ?

 E_ERROR: Nesting level too deep - recursive dependency? (/var/core/vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/TypeConverter.php:103)

**Comment by ArabCoders** [comment] 2016-05-01 06:56
i fixed it by changing

```php
return $array === [] || is_numeric( array_keys($array)[0]);
```

to 

```php
return $array === [] || is_numeric( $array[ key( $array ) ] );
```

**Comment by alcaeus** [comment] 2016-05-01 18:01
This was previously reported as #100 but we couldn't track down what was causing it. Could you share a document that produces the error or the stack trace that accompanies it? That would help figure this out...

**Comment by ArabCoders** [comment] 2016-05-01 18:28
sadly there isn't anything in mongo logs, and it seems the app does not log stack trace, the document the app working with was gridfs files if that would help, at the same time the app was experiencing the error, i was able to go to mongo shell and check the collection there was no problem.

i also tried to reproduce the error again by changing the lib back to what it was, but it seems the the db is temp file storage that had about 7k files in it and the data was removed.

**Comment by alcaeus** [comment] 2016-05-03 04:44
That's too bad. I took a look and found that each subdocument adds one nesting layer, so whether you will run into this issue depends on two factors:
1. The structure of your document. The more levels of embedded documents your root document contains, the sooner you're going to hit the limit
2. The code sorrounding the call. Since this library replaces `ext-mongo`, it will always be downstream from Doctrine ODM or another DBAL. If your code is heavily nested already (e.g. a Symfony application using Doctrine ODM) you'll run into problems sooner.

That being said, I'm not sure there's anything I can do about this. Using recursion is the only way I can ensure embedded documents are properly converted and we seem to run into arbitrary, non-changeable limits here.

If you want to try to reproduce this, try creating documents with different levels of embedded data and reading them from the same context (e.g. controller) they were read from when you first got the error. To fetch a trace, simply attach an error handler, look for the error in question and dump the trace.
```
{
    _id: 'embeddedSingle',
    embedded: { 'foo': true }
},
{
    _id: 'embeddedDouble',
    embedded: {
        embedded: { 'foo': true }
    }
}
```

**Comment by alcaeus** [comment] 2017-04-12 05:48
Closing - if anyone is still getting this issue, please open a new ticket.

**Closed by alcaeus** 2017-04-12 05:48 UTC
