### ISSUE TITLE
Installing mongo-php-adapter via composer

### ISSUE THREAD

**Issue by mike22** [alcaeus/mongo-php-adapter#30] opened 2016-01-18 08:13 UTC
Hi, I'm trying to find a solution for creating project with PHP7, Symfony3, MongoDB 3+, Doctrine combination. Doctrine ODM is not yet compatible...This mongo-php-adapter was suggested as workaround. But when I try to install it via composer in my symfony project I get the error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ext-mongo 1.6.12 -> satisfiable by ext-mongo[1.6.12].
    - don't install alcaeus/mongo-php-adapter dev-master|remove ext-mongo 1.6.12
    - Installation request for alcaeus/mongo-php-adapter dev-master -> satisfiable by alcaeus/mongo-php-adapter[dev-master].

So it expects ext-mongo 1.6.12 to be installed? But that's the main reason I have to use mongo-php-adapater...that ext-mongo 1.6.12 could not be installed for php7.
Am I missing something?
Thank you for your answer.

**Comment by peterrehm** [comment] 2016-01-18 10:38
I am still looking at the proper way and I am still getting errors around that. What helped me then resolving it was running `composer update --ignore-platform-reqs` once and then I was able to execute the update without the ignored platform reqs. 

As I am playing around with it I might find a better way. Adding a provide section to the composer.json in the project root did not help me, it just made it not installable at all. https://github.com/alcaeus/mongo-php-adapter/pull/27 It seems it is not yet ideal.

**Comment by alcaeus** [comment] 2016-01-18 11:46
@peterrehm Thanks for your input. I'll take another look at this tonight and see if I can find a configuration that works. I'd like to have this working without `--ignore-platform-reqs`.

**Comment by mike22** [comment] 2016-01-18 12:14
@peterrehm hm, I got the same error even with --ignore-platform-reqs option on....strange

**Comment by peterrehm** [comment] 2016-01-18 12:20
@mike22 Which deoendencies do you have in your composer.json?

**Comment by mike22** [comment] 2016-01-18 12:24
I will post you whole composer.json

{
    "name": "georg/trackino",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "require": {
        "php": ">=5.5.8",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "jms/serializer-bundle" : ">=0.1",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
	    "doctrine/mongodb-odm": "^1.0.4",
	    "doctrine/mongodb-odm-bundle": "3.1.*@dev",
        "mongodb/mongodb":"@beta"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^2.7"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}

**Comment by peterrehm** [comment] 2016-01-18 12:30
You ar missing  "alcaeus/mongo-php-adapter" and the mongodb deps shoul be dev-master for now.

Try:

    "doctrine/mongodb": "dev-master",
    "doctrine/mongodb-odm": "dev-master",
    "doctrine/mongodb-odm-bundle": "dev-master",
    "mongodb/mongodb":"@beta",
    "alcaeus/mongo-php-adapter": "dev-master",

**Comment by mike22** [comment] 2016-01-18 12:43
somehow I have menaged to install it...thank you very much for the help :)

**Comment by peterrehm** [comment] 2016-01-18 13:30
Your welcome, whenever I had issues I removed the entire vendor directory and did a new update. There is still something wrong and I have not found the solution yet. Maybe @alcaeus finds a better way :)

**Comment by alcaeus** [comment] 2016-01-18 18:05
I've managed to get this minimal composer.json installed:
```
{
    "type": "package",
    "name": "alcaeus/adapter-test",
    "replace": {
        "ext-mongo": "1.6.12"
    },
    "require": {
        "alcaeus/mongo-php-adapter": "dev-composer-install",
        "doctrine/mongodb-odm": "dev-master",
        "doctrine/mongodb": "dev-master",
        "mongodb/mongodb": "@beta"
    }
}
```

The `dev-composer-install` branch changes the `replace` to `provide`, which fixes an error @peterrehm was having previously. However, as @seldaek noted in a Twitter discussion with me, the root package must specify either `provide` or `replace` for `ext-mongo` as well (as was noted in the readme before #27).

**Comment by peterrehm** [comment] 2016-01-18 18:12
What happens if you try `provide` instead of `replace`? I was not able to get it up and running with `provide` in the root composer.json at all. Is this fixed with your change?

**Comment by alcaeus** [comment] 2016-01-18 18:20
In the composer.json you're installing, nothing. In the composer.json for the adapter:
```
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for alcaeus/adapter-test No version set (parsed as 1.0.0) -> satisfiable by alcaeus/adapter-test[No version set (parsed as 1.0.0)].
    - don't install alcaeus/mongo-php-adapter dev-master|remove alcaeus/adapter-test No version set (parsed as 1.0.0)
    - Installation request for alcaeus/mongo-php-adapter dev-master -> satisfiable by alcaeus/mongo-php-adapter[dev-master].
```

**Comment by peterrehm** [comment] 2016-01-18 18:33
That's so weird. Now it works for me 

````json
    "require": {
        "php": ">=7.0.2",
        "ext-mongodb": ">=1.1.2",
        "doctrine/mongodb-odm-bundle": "dev-master",
        "alcaeus/mongo-php-adapter": "dev-composer-install",
        "mongodb/mongodb": "@beta",
        "doctrine/mongodb": "dev-master"
        //...
    },
    "provide": {
        "ext-mongo": "1.6.12"
    },
````

But now it works not with replace. With replace I get like

````
  [Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for my/proj dev-php7 -> satisfiable by my/proj[dev-php7].
      - remove my/proj dev-php7|remove alcaeus/mongo-php-adapter dev-composer-install
      - Installation request for alcaeus/mongo-php-adapter dev-composer-install -> satisfiable by alcaeus/mongo-php-adapter[dev-c
  omposer-install].
````

**Comment by alcaeus** [comment] 2016-01-19 17:30
In the following table, the branches are:
* dev-master: uses `replace`
* dev-composer-install: uses `provide`

adapter | root-package | Result
------- | ------------ | ------
`dev-master` | `provide` | Fail
`dev-master` | `replace` | Fail
`dev-master` | Nothing | Fail
`dev-composer-install` | `provide` | Success
`dev-composer-install` | `replace` | Success
`dev-composer-install` | Nothing | Fail

Based on these findings, I've created #31.

**Comment by dzuelke** [comment] 2016-02-22 22:49
Revisiting this... I believe if might be important that *any* package installed requires `ext-mongo` for this to work: https://github.com/composer/composer/issues/2690

So just "replace" or "provide" alone won't cut it; either a dependency or root `composer.json` also need to contain `ext-mongo` as a requirement.

If that's true (from my limited testing, it is), then this package should switch to "replace" only and remind people that they or one of their dependencies need to require "ext-mongo".

**Comment by dzuelke** [comment] 2016-02-23 00:31
See #70

**Comment by alcaeus** [comment] 2016-02-25 07:05
@dzuelke revisited this after our chat last night and gisted the result: https://gist.github.com/alcaeus/c10ef3ce0ff18209de3d

A bit of context here: I remember there being some issues when I tested this, fortunately I still had the files around. Somewhere in the middle of my testing I remembered installing `composer` via `brew`, which of course installs Alpha-11. The results, of course, look quite different with the most recent version of composer, which is why I added it as a comment.

With all of this in mind, I'm reopening this for resolution before release 1.0.0.

**Comment by alcaeus** [comment] 2016-02-25 07:06
In single linkable form, these are the issues that may affect your output:
* Do you have `ext-mongo` installed at all?
* Which version of `ext-mongo` is installed?
* Which version of `composer` are you using?

**Comment by akd3vs** [comment] 2016-05-12 18:04
In Ubuntu 16.04 there's no ext-mongo as it is deprecated. This library can't be installed without ext-mongo?

**Comment by peterrehm** [comment] 2016-05-12 19:07
You need ext-mongodb installed and the proper replace/provide configuration.

**Comment by Manhim** [comment] 2016-06-11 15:05
I fixed this issue by remove any doctrine/* packages from my require, updating, then putting them back and updating again. I think that composer doesn't include "provide" or "replace" when checking for dependencies (I could be wrong).

**Comment by alcaeus** [comment] 2016-06-13 05:24
That's probably another workaround around the composer problem mentioned above. There's a good writeup in composer/composer#5030. TL;DR: it's an issue in how composer handles `ext-*` packages and packages that provide such an extension.

**Comment by c33s** [comment] 2016-08-19 01:26
- os: win
- php: 7.0.9 x64
- composer: 1.0.3 & 1.2.0
- mongodb version: [1.1.8][1] (as today the highest stable version, for v1.2.0 alpha there are no precompiled dlls

feedback from my installation. first it was not possible for me to get it to work. all time i got an 

> Your requirements could not be resolved to an installable set of packages.

tried:
```
"php": ">=5.5.9",
"doctrine/mongodb-odm": "*"

php: '>=5.5.9'
doctrine/mongodb-odm: '*'
ext-mongo: '*'

alcaeus/mongo-php-adapter:                      ~1.0
doctrine/mongodb-odm-bundle:                    ~3.2

"php": "^7.0",
"alcaeus/mongo-php-adapter": "^1.0.0",
"doctrine/mongodb": "dev-master"
...
```

nothing worked for me. my working solution is:

first add
```
    alcaeus/mongo-php-adapter:                      ~1.0
```
run
```
composer update
```
then add
```
    doctrine/mongodb-odm-bundle:                    ~3.2
```
and run 
```
composer update
```
again. this is the only way for me to install it. fist i had `'*'` as version number for both in it but it installed `1.0.5` and `3.2.0` so i directly entered the versions then.

```
composer install
```
works also if i delete the `vendor` directory before.



[1]: http://windows.php.net/downloads/pecl/releases/mongodb/1.1.8/

**Comment by alcaeus** [comment] 2016-08-19 07:44
Good of you to confirm this, I had the suspicion that some recent changes in composer broke the solution @dzuelke came up with before. For now, the only way to get other libraries that require `ext-mongo` working is to have a lock file which includes mongo-php-adapter. I'll have to try this, but IIRC it would also help adding the following repository configuration to composer.json:
```
repositories: [
    {
        'type': 'vcs',
        'url': 'https://github.com/alcaeus/mongo-php-adapter'
    }
]
```

**Comment by c33s** [comment] 2016-08-19 20:26
> some recent changes in composer

its quite interesting, that the problem also exists for the old composer version `1.0.3`, i thought maybe my composer version is too old and updated to `1.2.0` with the same result.

**Comment by alcaeus** [comment] 2016-08-20 10:02
> that the problem also exists for the old composer version `1.0.3`, i thought maybe my composer version is too old and updated to `1.2.0` with the same result.

Interesting - good to know. I'll have to check if there were some other changes and if the installation instructions need to be adapter. Thank you for the feedback!

**Comment by Th3Mouk** [comment] 2016-11-15 14:51
I've resolve my problem during deployment with Capistrano adding in the `composer.json` of the project:
```json
"provide": {
    "ext-mongo": "1.6.12"
}
```

I've confirm the fact that locally with a composer.lock the step by step requirement works. But all package at same time don't.

|  | Version |
| --- | --- |
| OS | Debian8|
| PHP Mongo.so | v1.1.9 |
| Composer | v1.2.2 |
| MongoDB package | v1.3.0 |

**Comment by dzuelke** [comment] 2016-11-15 16:46
To summarize the problem is still the same as it always has been: https://github.com/composer/composer/issues/5030

You cannot in one step add a requirement for this package and for `ext-mongo`. You must add this package first, re-generate the lock file using `composer update`, and then you can, in a separate step, require `ext-mongo`.

**Comment by alcaeus** [comment] 2017-01-29 08:27
Closing this issue. Composer doesn't quite support polyfills using `provide` or `replace` for extensions. Maybe composer 2.0 will bring some improvements.

**Closed by alcaeus** 2017-01-29 08:27 UTC
Labels: bug

**Comment by bailoo** [comment] 2018-02-12 09:22
I am facing this same issue with PHP 7.0.22-0ubuntu0.16.04.1
- alcaeus/mongo-php-adapter 1.1.4 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.

What is the current status on this  and work around ?

**Comment by alcaeus** [comment] 2018-02-12 09:33
This is an entirely different issue. This library provides the classes normally provided by the legacy extension (ext-mongo) on top of the new extension (ext-mongodb). As such, you have to install ext-mongodb, as suggested by the error message.

This issue is about a composer problem where this library can’t reliably tell it that ext-mongo is provided. The workaround is part of the installation instructions. You still have to install ext-mongodb though.
