### ISSUE TITLE
install mango php adapter with composer and use php.ini ?

### ISSUE THREAD

**Issue by muhammedInan** [alcaeus/mongo-php-adapter#267] opened 2020-01-14 09:57 UTC
Hi,

- alcaeus/mongo-php-adapter 1.1.4 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.

when I launch the command for install this require , I have this error howewer I add php_mangodb.dll in php.ini and in php/ext. In my composer .json its ^1.2.0

After try php-m I have nothing about mango

what more should i do please .

**Comment by alcaeus** [comment] 2020-01-15 08:02
Duplicate of #266.

**Closed by alcaeus** 2020-01-15 08:02 UTC
