### ISSUE TITLE
Drop in Performance compared to \MongoClient() or mongo-php-library

### ISSUE THREAD

**Issue by ggraf** [alcaeus/mongo-php-adapter#124] opened 2016-08-01 11:17 UTC
I'm about to migrate a PHP webapplication w/ MongoDB as main database to PHP7.

The adapter works quite good as drop in replacement.

When I did some performance tests i noted a significant drop in performance.

I iterated over a collection w/ ~1.000.000 documents and got following execution time results:
- php5 ~5sec (legacy \MongoClient())
- php7 ~6-7 sec (w/ mongo-php-library)
- php7 ~18 sec (w/ mongo-php-adapter+mongo-php-library)

[...]
$coll = $mongo->selectCollection('examples.demo');
$allDocs = $coll->find();
foreach ($allDocs as $doc) {
[...]

Are there any possible tweaks to get the execution time down to be in the same time range as the mongo-php-library?

**Comment by alcaeus** [comment] 2016-08-01 11:32
> Are there any possible tweaks to get the execution time down to be in the same time range as the mongo-php-library?

I haven't really done any performance testing yet. I suspect the problem being in the type conversion. I'll see if I can create a few performance test cases and start profiling the code to see where it could be optimized.

**Comment by alcaeus** [comment] 2016-08-01 19:03
This is going to be tricky and, I'm afraid, mostly unpleasant. I created two small sample scripts. Both read data from the same collection containing 10k records, only consisting of an ObjectID and a counter. One script reads from the table using `MongoCollection`, the other uses `MongoDB\Collection`:
```php
$client = new MongoClient();
$collection = $client->selectCollection('performance', 'tenthousand');

$documents = $collection->find();
foreach ($documents as $doc)
{
}
```
```php
$client = new \MongoDB\Client();
$collection = $client->selectCollection('performance', 'tenthousand');

$documents = $collection->find();
foreach ($documents as $doc)
{
}
```

The baseline results are not promising to begin with, as you've mentioned yourself:
```
$ time php test-mongo.php

real	0m0.364s
user	0m0.322s
sys	0m0.016s

$ time php test-mongodb.php

real	0m0.087s
user	0m0.052s
sys	0m0.014s
```

So I profiled the script and as expected, most time is spent doing time conversion:
![image](https://cloud.githubusercontent.com/assets/383198/17305341/464a29d6-582a-11e6-9061-be54557aba81.png)

The code to fault here is exactly the kind of code required to get old libraries compatible with the new driver: conversion from the new BSON types to the old legacy types. The problem isn't that it's slow, it just adds up. For example, a single call to `MongoId::__construct` takes all of 27 microseconds. When it has to be done 10000 times that still adds up to 270ms, or in the case of this run, about 10% of the time spent.
Similarly, every time a `BSONDocument` or `BSONArray` instance is spotted, `TypeConverter::toLegacy` has to iterate over it.

That being said, now that I know what the issues are, I'll try to fix them. Maybe reducing the amount of nested function calls would help make it faster, maybe I can optimize some of the type handling to be generally faster. However, I don't expect to make it significantly faster - that is the penalty associated with that kind of built-on-top conversion.

**Comment by alcaeus** [comment] 2017-04-12 05:48
Closing for now - I'll revisit this once BSON type conversion can be done natively in the PHP driver. It has been implemented in the HHVM driver and should be in the next minor release of ext-mongodb for PHP. Thank you for the patience.

**Closed by alcaeus** 2017-04-12 05:48 UTC
Labels: bug

**Comment by ahmedmhmd** [comment] 2018-08-04 02:25
@alcaeus any workaround to this problem? MongoDB ODM 2.0 doesn't seem to have a precise launch date

**Comment by alcaeus** [comment] 2018-08-06 05:35
No - unfortunately, type conversion in the driver was scrapped, so there's nothing I can really do. I'd rather invest my time in finishing ODM 2.0 - we're close to an alpha but there are a couple of open issues.
